### ISSUE TITLE
execute_pdadmin role

### ISSUE THREAD

**Issue by dcrask** [IBM-Security/isam-ansible-collection#79]
I have created a playbook using the execute_pdadmin role.   I am able to successfully make most pdadmin commands but when I try to perform a group import it fails.  I am able to execute the test command on the isam appliance "group import test cn=test,ou=Groups,cn=Users"  but when I attempt via ansible it errors and appears to be parsing the commas.   I have attempted multiple iterations and not been able to execute the pdadmin group import via ansible.  Has anyone else gotten this to work?

**Comment by ram-ibm** [comment]
Perhaps if you can provide the options you tried and the error you got - we can figure out what the issue is?

Here is a sample that works for me:
"group import MyGroup \"cn=MyGroup,ou=groups,o=ibm,c=us\""

**Comment by ram-ibm** [comment]
Let me try that again:
```
"group import MyGroup \"cn=MyGroup,ou=groups,o=ibm,c=us\""
```

**Comment by dcrask** [comment]
This is what I am trying that fails:
"group import test "cn=test,ou=Groups,cn=Users""
![image](https://user-images.githubusercontent.com/51930288/98549827-52250380-2269-11eb-8cd5-f3f85da61588.png)

**Comment by dcrask** [comment]
I also tried "group import test \"cn=test,ou=Groups,cn=Users\""
which failed the same way.

**Comment by ram-ibm** [comment]
Please provide details of the playbook you are using to execute. Escaping double quotes using a backslash has worked for me.

**Comment by dcrask** [comment]
I have tried multiple iterations but this is my most recent playbook:
#---
# Run PDAdmin commands - against all but restricted appliances

- name: Run PDAdmin command(s) against an appliance
  hosts: "{{ hosts | default('sandbox')}}"
  connection: local
  gather_facts: no
  vars_prompt:
    - name: "username"
      prompt: "What is your username?"
      private: no

    - name: password
      prompt: "What is your password?"
  vars:
#    pdadmin_commands: "{{ lookup('file', 'cmds.pdadmin2') }}"
    pdadmin_commands: "group import test \"cn=test,ou=Groups,cn=Users\""
    lmi_port: 443

  roles:
    - role: execute_pdadmin
      execute_pdadmin_commands: "{{pdadmin_commands}}"
      execute_pdadmin_isamuser: "sec_master"
#      execute_pdadmin_isamuser: "{{sec_master_id}}"
#      execute_pdadmin_isampwd:  "{{sec_master_pwd}}"
      execute_pdadmin_isampwd:  "admin"
      execute_pdadmin_domain: "Default"
#       execute_pdadmin_domain: "{{ admin_domain }}"

**Comment by dcrask** [comment]
I have used the same playbook to successfully create an ACL  using pdamin_commands: "acl create testacl"

**Comment by svetterIO** [comment]
Normally the pdadmin_commands is a list of commands. e.g.
```
pdadmin_commands:
  - "group import test cn=test,ou=Groups,cn=Users"
```

I wonder how did you execute the role to get the failed output ? Because I always get a stacktrace like
```
TASK [ibm.isam.execute_pdadmin : Run PDAdmin commands] ************************************************************************************************************************************************************************************************************************
task path: /home/User/.ansible/collections/ansible_collections/ibm/isam/roles/web/execute_pdadmin/tasks/pdadmin.yml:1
<isva-1.ibm.com> ESTABLISH LOCAL CONNECTION FOR USER: User
<isva-1.ibm.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/User/.ansible/tmp/ansible-local-2908rjyvzub0 `"&& mkdir /home/User/.ansible/tmp/ansible-local-2908rjyvzub0/ansible-tmp-1605273855.0324328-2913-165458977350439 && echo ansible-tmp-1605273855.0324328-2913-165458977350439="` echo /home/User/.ansible/tmp/ansible-local-2908rjyvzub0/ansible-tmp-1605273855.0324328-2913-165458977350439 `" ) && sleep 0'
<isva-1.ibm.com> Attempting python interpreter discovery
<isva-1.ibm.com> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<isva-1.ibm.com> Python interpreter discovery fallback (unsupported platform for extended discovery: cygwin_nt-10.0)
Using module file /home/User/.ansible/collections/ansible_collections/ibm/isam/plugins/modules/isamadmin.py
<isva-1.ibm.com> PUT /home/User/.ansible/tmp/ansible-local-2908rjyvzub0/tmpuvmdn2jc TO /home/User/.ansible/tmp/ansible-local-2908rjyvzub0/ansible-tmp-1605273855.0324328-2913-165458977350439/AnsiballZ_isamadmin.py
<isva-1.ibm.com> EXEC /bin/sh -c 'chmod u+x /home/User/.ansible/tmp/ansible-local-2908rjyvzub0/ansible-tmp-1605273855.0324328-2913-165458977350439/ /home/User/.ansible/tmp/ansible-local-2908rjyvzub0/ansible-tmp-1605273855.0324328-2913-165458977350439/AnsiballZ_isamadmin.py && sleep 0'
<isva-1.ibm.com> EXEC /bin/sh -c '/usr/bin/python3.7 /home/User/.ansible/tmp/ansible-local-2908rjyvzub0/ansible-tmp-1605273855.0324328-2913-165458977350439/AnsiballZ_isamadmin.py && sleep 0'
<isva-1.ibm.com> EXEC /bin/sh -c 'rm -f -r /home/User/.ansible/tmp/ansible-local-2908rjyvzub0/ansible-tmp-1605273855.0324328-2913-165458977350439/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/User/.ansible/tmp/ansible-local-2908rjyvzub0/ansible-tmp-1605273855.0324328-2913-165458977350439/AnsiballZ_isamadmin.py", line 102, in <module>
    _ansiballz_main()
  File "/home/User/.ansible/tmp/ansible-local-2908rjyvzub0/ansible-tmp-1605273855.0324328-2913-165458977350439/AnsiballZ_isamadmin.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/User/.ansible/tmp/ansible-local-2908rjyvzub0/ansible-tmp-1605273855.0324328-2913-165458977350439/AnsiballZ_isamadmin.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.ibm.isam.plugins.modules.isamadmin', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_ibm.isam.isamadmin_payload_m3mh5815/ansible_ibm.isam.isamadmin_payload.zip/ansible_collections/ibm/isam/plugins/modules/isamadmin.py", line 55, in <module>
  File "/tmp/ansible_ibm.isam.isamadmin_payload_m3mh5815/ansible_ibm.isam.isamadmin_payload.zip/ansible_collections/ibm/isam/plugins/modules/isamadmin.py", line 38, in main
  File "/tmp/ansible_ibm.isam.isamadmin_payload_m3mh5815/ansible_ibm.isam.isamadmin_payload.zip/ansible/module_utils/connection.py", line 185, in __rpc__
ansible.module_utils.connection.ConnectionError: Error> IBMError
[WARNING]: Platform cygwin_nt-10.0 on host isva-1.ibm.com is using the discovered Python interpreter at /usr/bin/python3.7, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.
fatal: [isva-1.ibm.com]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3.7"
    },
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/User/.ansible/tmp/ansible-local-2908rjyvzub0/ansible-tmp-1605273855.0324328-2913-165458977350439/AnsiballZ_isamadmin.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/User/.ansible/tmp/ansible-local-2908rjyvzub0/ansible-tmp-1605273855.0324328-2913-165458977350439/AnsiballZ_isamadmin.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/User/.ansible/tmp/ansible-local-2908rjyvzub0/ansible-tmp-1605273855.0324328-2913-165458977350439/AnsiballZ_isamadmin.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.ibm.isam.plugins.modules.isamadmin', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.7/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.7/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_ibm.isam.isamadmin_payload_m3mh5815/ansible_ibm.isam.isamadmin_payload.zip/ansible_collections/ibm/isam/plugins/modules/isamadmin.py\", line 55, in <module>\n  File \"/tmp/ansible_ibm.isam.isamadmin_payload_m3mh5815/ansible_ibm.isam.isamadmin_payload.zip/ansible_collections/ibm/isam/plugins/modules/isamadmin.py\", line 38, in main\n  File \"/tmp/ansible_ibm.isam.isamadmin_payload_m3mh5815/ansible_ibm.isam.isamadmin_payload.zip/ansible/module_utils/connection.py\", line 185, in __rpc__\nansible.module_utils.connection.ConnectionError: Error> IBMError\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
...ignoring
```
from your sample command.
I need to add a successful command at the end of my list e.g.
```
pdadmin_commands:
  - "group import test cn=test,ou=Groups,cn=Users"
  - exit
```
to get proper output:
```
TASK [ibm.isam.execute_pdadmin : Output of PDAdmin command execution] *********************************************************************************************************************************************************************************************************
task path: /home/User/.ansible/collections/ansible_collections/ibm/isam/roles/web/execute_pdadmin/tasks/pdadmin.yml:14
ok: [isva-1.ibm.com] => {
    "msg": [
        "cmd> \\# Import AD Groups",
        "Error: Unknown command. Try using 'help' for a list of commands",
        "cmd> group import test cn=test,ou=Groups,cn=Users",
        "Could not perform the administration request",
        "Error: HPDMG1068E   An invalid group identification or Distinguished Name (DN) was specified. (status 0x14c0142c)",
        "cmd> exit"
    ]
}
```

Btw. from your screenshot it seems like you're also passing a comment `# Import AD Groups` to the appliance.

Which version of ISAM/ISVA and ansible are you using ?

**Comment by ram-ibm** [comment]
I suspect you want to read pdadmin command from a file to execute? If so check this issue out - using a cat command helped:
https://github.com/IBM-Security/isam-ansible-roles/issues/55

```
---
# PDAdmin - create a file with the commands and pass it via pdadmin_cmds variable

- name: Run PDAdmin command(s) against an appliance
  hosts: all
  connection: local
  pre_tasks:
    - name: Read pdadmin commands into variable
      command: "cat {{pdadmin_cmds}}"
      register: pdadmin_cmds_var
      run_once: True
      changed_when: False
  roles:
    - role: execute_pdadmin
      execute_pdadmin_commands: "{{ pdadmin_cmds_var.stdout_lines }}"
      execute_pdadmin_isamuser: "{{sec_master_id}}"
      execute_pdadmin_isampwd:  "{{sec_master_pwd}}"
      when: pdadmin_cmds is defined and pdadmin_cmds_var is defined
```

**Comment by dcrask** [comment]
Thanks, really appreciate your help!!  Using the last 2 updates I was able to get my pdadmin group import ansible playbook to run successfully.  @svetterIO-We are on 9.0.7 and we have AD setup as a federated directory, as such we import the groups for use with some ACLs.
